FROM       golang:1.20.3 as builder
WORKDIR    /src/
COPY       . ./
RUN        CGO_ENABLED=0 go build -o bin/payments ./app/services/payments

FROM       scratch
WORKDIR    /go/
COPY       --from=builder /src/bin/payments ./
EXPOSE     8000
ENTRYPOINT ["./payments"]
