FROM       golang:1.20.3 as builder
WORKDIR    /src/
COPY       . ./
RUN        CGO_ENABLED=0 go build -o bin/property ./app/services/property

FROM       scratch
WORKDIR    /go/
COPY       --from=builder /src/bin/property ./
EXPOSE     8001
ENTRYPOINT ["./property"]
