###
# @name createInvoice
POST http://localhost:8000/v1/managers/f81c2348-e72b-4f41-b764-eb92aa19f043/properties/d5205478-a82a-4044-822d-079639a9fe17/invoices
Content-Type: application/json

{
    "tenantId": "f81c2348-e72b-4f41-b764-eb92aa19f043",
    "dueDate": "2023-09-26"
}

###
# @name createPayment
@invoiceId = {{createInvoice.response.body.$.invoice.id}}
POST http://localhost:8000/v1/tenants/f81c2348-e72b-4f41-b764-eb92aa19f043/invoices/{{invoiceId}}/payments
Content-Type: application/json

{
    "amount": 200
}

###
# @name listPaymentHistory
GET http://localhost:8000/v1/tenants/f81c2348-e72b-4f41-b764-eb92aa19f043/payments/history
Content-Type: application/json
