###
# @name createManager
POST http://localhost:8001/v1/managers
Content-Type: application/json

{
    "entity": "biz"
}

###
# @name createProperty
@managerId = {{createManager.response.body.$.manager.id}}
POST http://localhost:8001/v1/managers/{{managerId}}/properties
Content-Type: application/json

{
    "street": "200 nw 95 street",
    "city": "plantation",
    "state": "fl",
    "rent": 1000,
    "postalCode": "33324",
    "name": "biz apartment",
    "type": "APARTMENT",
    "unitNumber": 4
}

###
# @name getProperty
@propertyId = {{createProperty.response.body.$.property.id}}
GET http://localhost:8001/v1/managers/{{managerId}}/properties/{{propertyId}}

###
# @name updateProperty
PATCH http://localhost:8001/v1/managers/{{managerId}}/properties/{{propertyId}}
Content-Type: application/json

{
    "name": "new biz apartment",
    "rent": 500
}

###
# @name listProperties
GET http://localhost:8001/v1/managers/{{managerId}}/properties

###
# @name createTenant
POST http://localhost:8001/v1/managers/{{managerId}}/properties/{{propertyId}}/tenants
Content-Type: application/json

{
    "firstName": "mike",
    "lastName": "jon",
    "dateOfBirth": "1987-04-12",
    "ssn": 876568743,
    "type": "PRIMARY"
}

###
# @name getTenant
@tenantId = {{createTenant.response.body.$.tenant.id}}
GET http://localhost:8001/v1/managers/{{managerId}}/properties/{{propertyId}}/tenants/{{tenantId}}

###
# @name updateTenant
PATCH http://localhost:8001/v1/managers/{{managerId}}/properties/{{propertyId}}/tenants/{{tenantId}}
Content-Type: application/json

{
    "newPropertyId": "96e98f4f-e4a5-4d9c-9077-507f633d218c",
    "type": "SECONDARY"
}

###
# @name listTenants
GET http://localhost:8001/v1/managers/{{managerId}}/properties/{{propertyId}}/tenants
